# Generated by Django 5.0.6 on 2024-06-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(default='toyota', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model_year',
            field=models.IntegerField(default=2022),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(default='KDN ', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
